# TCL File Generated by Component Editor 25.1
# Sun Jul 20 09:56:47 CEST 2025
# DO NOT MODIFY


# 
# one_ai_interface "ONE_AI_Interface" v1.0
#  2025.07.20.09:56:47
# 
# 

# 
# request TCL package from ACDS 25.1
# 
package require -exact qsys 25.1


# 
# module one_ai_interface
# 
set_module_property DESCRIPTION ""
set_module_property NAME one_ai_interface
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property BSP_CPU false
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ONE_AI_Interface
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0
set_module_property PRE_COMP_MODULE_ENABLED false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ONE_AI_Interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ONEAI_Config_Package.vhd VHDL PATH one_ai/ONEAI_Config_Package.vhd
add_fileset_file ONEAI_Data_Package.vhd VHDL PATH one_ai/ONEAI_Data_Package.vhd
add_fileset_file ONEAI_Top.vhd VHDL PATH one_ai/ONEAI_Top.vhd
add_fileset_file ONE_AI_Interface.vhd VHDL PATH ONE_AI_Interface.vhd TOP_LEVEL_FILE
add_fileset_file CNN_Convolution.vhd VHDL PATH one_ai/Core/CNN_Convolution.vhd
add_fileset_file CNN_Normalization.vhd VHDL PATH one_ai/Core/CNN_Normalization.vhd
add_fileset_file CNN_Pooling_Efficient.vhd VHDL PATH one_ai/Core/CNN_Pooling_Efficient.vhd
add_fileset_file CNN_Row_Buffer.vhd VHDL PATH one_ai/Core/CNN_Row_Buffer.vhd
add_fileset_file CNN_Row_Expander.vhd VHDL PATH one_ai/Core/CNN_Row_Expander.vhd
add_fileset_file NN_Layer.vhd VHDL PATH one_ai/Core/NN_Layer.vhd
add_fileset_file Crop_Filter.vhd VHDL PATH one_ai/Filters/Crop_Filter.vhd
add_fileset_file Inverse_Filter.vhd VHDL PATH one_ai/Filters/Inverse_Filter.vhd
add_fileset_file Normalize_Filter.vhd VHDL PATH one_ai/Filters/Normalize_Filter.vhd
add_fileset_file Reduce_To_Brightness.vhd VHDL PATH one_ai/Filters/Reduce_To_Brightness.vhd
add_fileset_file Threshold_Filter.vhd VHDL PATH one_ai/Filters/Threshold_Filter.vhd


# 
# parameters
# 
add_parameter BUFFER_BASE_ADDR STD_LOGIC_VECTOR 524288
set_parameter_property BUFFER_BASE_ADDR DEFAULT_VALUE 524288
set_parameter_property BUFFER_BASE_ADDR DISPLAY_NAME BUFFER_BASE_ADDR
set_parameter_property BUFFER_BASE_ADDR WIDTH 32
set_parameter_property BUFFER_BASE_ADDR UNITS None
set_parameter_property BUFFER_BASE_ADDR ALLOWED_RANGES 0:4294967295
set_parameter_property BUFFER_BASE_ADDR AFFECTS_GENERATION false
set_parameter_property BUFFER_BASE_ADDR HDL_PARAMETER true
set_parameter_property BUFFER_BASE_ADDR TRANSFORM_PARAMETER false
set_parameter_property BUFFER_BASE_ADDR EXPORT true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""
set_interface_property clock IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property clock SV_INTERFACE_TYPE ""
set_interface_property clock SV_INTERFACE_MODPORT_TYPE ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""
set_interface_property reset IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property reset SV_INTERFACE_TYPE ""
set_interface_property reset SV_INTERFACE_MODPORT_TYPE ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_master_0
# 
add_interface avalon_master_0 avalon start
set_interface_property avalon_master_0 addressGroup 0
set_interface_property avalon_master_0 addressUnits SYMBOLS
set_interface_property avalon_master_0 associatedClock clock
set_interface_property avalon_master_0 associatedReset reset
set_interface_property avalon_master_0 bitsPerSymbol 8
set_interface_property avalon_master_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_master_0 burstcountUnits WORDS
set_interface_property avalon_master_0 doStreamReads false
set_interface_property avalon_master_0 doStreamWrites false
set_interface_property avalon_master_0 holdTime 0
set_interface_property avalon_master_0 linewrapBursts false
set_interface_property avalon_master_0 maximumPendingReadTransactions 0
set_interface_property avalon_master_0 maximumPendingWriteTransactions 0
set_interface_property avalon_master_0 minimumResponseLatency 1
set_interface_property avalon_master_0 readLatency 0
set_interface_property avalon_master_0 readWaitTime 1
set_interface_property avalon_master_0 setupTime 0
set_interface_property avalon_master_0 timingUnits Cycles
set_interface_property avalon_master_0 waitrequestAllowance 0
set_interface_property avalon_master_0 waitrequestTimeout 1024
set_interface_property avalon_master_0 writeWaitTime 0
set_interface_property avalon_master_0 enableConcurrentSubordinateAccess 0
set_interface_property avalon_master_0 optimizedReadsWithBE 0
set_interface_property avalon_master_0 ENABLED true
set_interface_property avalon_master_0 EXPORT_OF ""
set_interface_property avalon_master_0 PORT_NAME_MAP ""
set_interface_property avalon_master_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master_0 SVD_ADDRESS_GROUP ""
set_interface_property avalon_master_0 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property avalon_master_0 SV_INTERFACE_TYPE ""
set_interface_property avalon_master_0 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port avalon_master_0 avm_address address Output 32
add_interface_port avalon_master_0 avm_read read Output 1
add_interface_port avalon_master_0 avm_readdata readdata Input 32
add_interface_port avalon_master_0 avm_waitrequest waitrequest Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressGroup 0
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 bridgedAddressOffset ""
set_interface_property avalon_slave_0 bridgesToMaster ""
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 minimumResponseLatency 1
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 transparentBridge false
set_interface_property avalon_slave_0 waitrequestAllowance 0
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 dfhFeatureGuid 0
set_interface_property avalon_slave_0 dfhGroupId 0
set_interface_property avalon_slave_0 dfhParameterId ""
set_interface_property avalon_slave_0 dfhParameterName ""
set_interface_property avalon_slave_0 dfhParameterVersion ""
set_interface_property avalon_slave_0 dfhParameterData ""
set_interface_property avalon_slave_0 dfhParameterDataLength ""
set_interface_property avalon_slave_0 dfhFeatureMajorVersion 0
set_interface_property avalon_slave_0 dfhFeatureMinorVersion 0
set_interface_property avalon_slave_0 dfhFeatureId 35
set_interface_property avalon_slave_0 dfhFeatureType 3
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""
set_interface_property avalon_slave_0 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property avalon_slave_0 SV_INTERFACE_TYPE ""
set_interface_property avalon_slave_0 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port avalon_slave_0 avs_address address Input 8
add_interface_port avalon_slave_0 avs_read read Input 1
add_interface_port avalon_slave_0 avs_readdata readdata Output 32
add_interface_port avalon_slave_0 avs_write write Input 1
add_interface_port avalon_slave_0 avs_writedata writedata Input 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point interrupt_receiver
# 
add_interface interrupt_receiver interrupt start
set_interface_property interrupt_receiver associatedClock clock
set_interface_property interrupt_receiver associatedReset reset
set_interface_property interrupt_receiver irqScheme INDIVIDUAL_REQUESTS
set_interface_property interrupt_receiver ENABLED true
set_interface_property interrupt_receiver EXPORT_OF ""
set_interface_property interrupt_receiver PORT_NAME_MAP ""
set_interface_property interrupt_receiver CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_receiver SVD_ADDRESS_GROUP ""
set_interface_property interrupt_receiver IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property interrupt_receiver SV_INTERFACE_TYPE ""
set_interface_property interrupt_receiver SV_INTERFACE_MODPORT_TYPE ""

add_interface_port interrupt_receiver frame_writer_irq irq Input 1

