
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Atum_A3_Nano(

	//////////// CLOCK //////////
	input 		          		CLOCK0_50,
	input 		          		CLOCK1_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [3:0]		LED,

	//////////// SW //////////
	input 		     [1:0]		SW,

	//////////// PMOD_0 //////////
	inout 		     [7:0]		TMD0_D,

	//////////// GPIO_D, GPIO connect to D8M-GPIO //////////
	inout 		          		CAMERA_I2C_SCL,
	inout 		          		CAMERA_I2C_SDA,
	output		          		CAMERA_PWDN_n,
	output		          		MIPI_CS_n,
	inout 		          		MIPI_I2C_SCL,
	inout 		          		MIPI_I2C_SDA,
	output		          		MIPI_MCLK,
	input 		          		MIPI_PIXEL_CLK,
	input 		     [9:0]		MIPI_PIXEL_D,
	input 		          		MIPI_PIXEL_HS,
	input 		          		MIPI_PIXEL_VS,
	output		          		MIPI_REFCLK,
	output		          		MIPI_RESET_n
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
// Reset Release
wire                reset_n;
wire                ninit_done;    

// MIPI PIXEL
wire                MIPI_PIXEL_CLK_d;
reg                 MIPI_PIXEL_VS_d;
reg                 MIPI_PIXEL_HS_d;
reg     [9:0]       MIPI_PIXEL_D_d;

// I2C
wire                camera_i2c_serial_sda_in;
wire                camera_i2c_serial_scl_in;
wire                camera_i2c_serial_sda_oe;
wire                camera_i2c_serial_scl_oe;

wire                mipi_i2c_serial_sda_in;
wire                mipi_i2c_serial_scl_in;
wire                mipi_i2c_serial_sda_oe;
wire                mipi_i2c_serial_scl_oe;
//=======================================================
//  Structural coding
//=======================================================
assign MIPI_PIXEL_CLK_d = ~MIPI_PIXEL_CLK;

always @ (posedge MIPI_PIXEL_CLK_d) begin
    MIPI_PIXEL_VS_d <= MIPI_PIXEL_VS;
    MIPI_PIXEL_HS_d <= MIPI_PIXEL_HS;
    MIPI_PIXEL_D_d  <= MIPI_PIXEL_D;
end

ResetRelease ResetRelease_inst (
    .ninit_done (ninit_done)  //  output,  width = 1, ninit_done.ninit_done
);

assign reset_n = ~ninit_done; 

assign MIPI_CS_n = 0;

assign camera_i2c_serial_scl_in = CAMERA_I2C_SCL;
assign camera_i2c_serial_sda_in = CAMERA_I2C_SDA;
assign CAMERA_I2C_SCL = camera_i2c_serial_scl_oe ? 1'b0 : 1'bz;
assign CAMERA_I2C_SDA = camera_i2c_serial_sda_oe ? 1'b0 : 1'bz;

assign mipi_i2c_serial_scl_in = MIPI_I2C_SCL;
assign mipi_i2c_serial_sda_in = MIPI_I2C_SDA;
assign MIPI_I2C_SCL = mipi_i2c_serial_scl_oe ? 1'b0 : 1'bz;
assign MIPI_I2C_SDA = mipi_i2c_serial_sda_oe ? 1'b0 : 1'bz;

system u0 (
    .clk_clk                                      (CLOCK0_50),                                      //   input,   width = 1,                              clk.clk
    .reset_n_reset_n                              (reset_n),                                  //   input,   width = 1,                            reset.reset

    .key_external_connection_export               (KEY),               //   input,   width = 2,          key_external_connection.export
    .led_external_connection_export               (LED),               //  output,   width = 3,          led_external_connection.export
    .sw_external_connection_export                (SW),                //   input,  width = 2,           sw_external_connection.export

    .terasic_auto_focus_0_conduit_clk50           (CLOCK0_50),           //   input,   width = 1,     terasic_auto_focus_0_conduit.clk50
    .terasic_auto_focus_0_conduit_vcm_i2c_scl     (CAMERA_I2C_SCL),     //   inout,   width = 1,                                 .vcm_i2c_scl
    .terasic_auto_focus_0_conduit_vcm_i2c_sda     (CAMERA_I2C_SDA),     //   inout,   width = 1,                                 .vcm_i2c_sda
    
    .i2c_camera_i2c_serial_sda_in                 (camera_i2c_serial_sda_in),                 //   input,   width = 1,            i2c_camera_i2c_serial.sda_in
    .i2c_camera_i2c_serial_scl_in                 (camera_i2c_serial_scl_in),                 //   input,   width = 1,                                 .scl_in
    .i2c_camera_i2c_serial_sda_oe                 (camera_i2c_serial_sda_oe),                 //  output,   width = 1,                                 .sda_oe
    .i2c_camera_i2c_serial_scl_oe                 (camera_i2c_serial_scl_oe),                 //  output,   width = 1,                                 .scl_oe

    .i2c_mipi_i2c_serial_sda_in                   (mipi_i2c_serial_sda_in),                   //   input,   width = 1,              i2c_mipi_i2c_serial.sda_in
    .i2c_mipi_i2c_serial_scl_in                   (mipi_i2c_serial_scl_in),                   //   input,   width = 1,                                 .scl_in
    .i2c_mipi_i2c_serial_sda_oe                   (mipi_i2c_serial_sda_oe),                   //  output,   width = 1,                                 .sda_oe
    .i2c_mipi_i2c_serial_scl_oe                   (mipi_i2c_serial_scl_oe),                   //  output,   width = 1,                                 .scl_oe
  
    .mipi_pwdn_n_external_connection_export       (CAMERA_PWDN_n),       //  output,   width = 1,  mipi_pwdn_n_external_connection.export
    .mipi_reset_n_external_connection_export      (MIPI_RESET_n),      //  output,   width = 1, mipi_reset_n_external_connection.export

    .lw_uart_0_external_connection_rxd            (TMD0_D[0]),          //   input,   width = 1,    lw_uart_0_external_connection.rxd
    .lw_uart_0_external_connection_txd            (TMD0_D[1]),          //  output,   width = 1,                                 .txd

    .d8m_xclkin_clk                               (MIPI_REFCLK),                               //  output,   width = 1,                       d8m_xclkin.clk
    .terasic_camera_0_conduit_end_camera_d        ({MIPI_PIXEL_D_d[9:0],2'b00}),        //   input,  width = 12,     terasic_camera_0_conduit_end.camera_d
    .terasic_camera_0_conduit_end_camera_fval     (MIPI_PIXEL_VS_d),     //   input,   width = 1,                                 .camera_fval
    .terasic_camera_0_conduit_end_camera_lval     (MIPI_PIXEL_HS_d),     //   input,   width = 1,                                 .camera_lval
    .terasic_camera_0_conduit_end_camera_pixclk   (MIPI_PIXEL_CLK_d)    //   input,   width = 1,                                 .camera_pixclk
    
);

endmodule
