# TCL File Generated by Component Editor 25.1
# Fri Aug 08 16:10:23 CST 2025
# DO NOT MODIFY


# 
# terasic_camera "TERASIC_CAMERA" v1.0
#  2025.08.08.16:10:23
# 
# 

# 
# request TCL package from ACDS 25.1
# 
package require -exact qsys 25.1


# 
# module terasic_camera
# 
set_module_property DESCRIPTION ""
set_module_property NAME terasic_camera
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property BSP_CPU false
set_module_property GROUP "Terasic Technologies Inc"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME TERASIC_CAMERA
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0
set_module_property PRE_COMP_MODULE_ENABLED false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL TERASIC_CAMERA
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Bayer2RGB.v VERILOG PATH Bayer2RGB.v
add_fileset_file CAMERA_Bayer.v VERILOG PATH CAMERA_Bayer.v
add_fileset_file CAMERA_RGB.v VERILOG PATH CAMERA_RGB.v
add_fileset_file rgb_fifo.v VERILOG PATH rgb_fifo/synth/rgb_fifo.v
add_fileset_file add2.v VERILOG PATH add2/synth/add2.v
add_fileset_file add4.v VERILOG PATH add4/synth/add4.v
add_fileset_file Bayer_LineBuffer.v VERILOG PATH Bayer_LineBuffer/synth/Bayer_LineBuffer.v
add_fileset_file TERASIC_CAMERA.v VERILOG PATH TERASIC_CAMERA.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter VIDEO_W INTEGER 800
set_parameter_property VIDEO_W DEFAULT_VALUE 800
set_parameter_property VIDEO_W DISPLAY_NAME VIDEO_W
set_parameter_property VIDEO_W UNITS None
set_parameter_property VIDEO_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property VIDEO_W AFFECTS_GENERATION false
set_parameter_property VIDEO_W HDL_PARAMETER true
set_parameter_property VIDEO_W TRANSFORM_PARAMETER false
set_parameter_property VIDEO_W EXPORT true
add_parameter VIDEO_H INTEGER 600
set_parameter_property VIDEO_H DEFAULT_VALUE 600
set_parameter_property VIDEO_H DISPLAY_NAME VIDEO_H
set_parameter_property VIDEO_H UNITS None
set_parameter_property VIDEO_H ALLOWED_RANGES -2147483648:2147483647
set_parameter_property VIDEO_H AFFECTS_GENERATION false
set_parameter_property VIDEO_H HDL_PARAMETER true
set_parameter_property VIDEO_H TRANSFORM_PARAMETER false
set_parameter_property VIDEO_H EXPORT true


# 
# display items
# 


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock_reset
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""
set_interface_property conduit_end IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property conduit_end SV_INTERFACE_TYPE ""
set_interface_property conduit_end SV_INTERFACE_MODPORT_TYPE ""

add_interface_port conduit_end CAMERA_D camera_d Input 12
add_interface_port conduit_end CAMERA_FVAL camera_fval Input 1
add_interface_port conduit_end CAMERA_LVAL camera_lval Input 1
add_interface_port conduit_end CAMERA_PIXCLK camera_pixclk Input 1


# 
# connection point axi4stream_master
# 
add_interface axi4stream_master axi4stream start
set_interface_property axi4stream_master associatedClock clock_reset
set_interface_property axi4stream_master associatedReset clock_reset_reset
set_interface_property axi4stream_master ENABLED true
set_interface_property axi4stream_master EXPORT_OF ""
set_interface_property axi4stream_master PORT_NAME_MAP ""
set_interface_property axi4stream_master CMSIS_SVD_VARIABLES ""
set_interface_property axi4stream_master SVD_ADDRESS_GROUP ""
set_interface_property axi4stream_master IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property axi4stream_master SV_INTERFACE_TYPE ""
set_interface_property axi4stream_master SV_INTERFACE_MODPORT_TYPE ""

add_interface_port axi4stream_master tdata tdata Output 24
add_interface_port axi4stream_master tvalid tvalid Output 1
add_interface_port axi4stream_master tuser tuser Output 3
add_interface_port axi4stream_master tlast tlast Output 1
add_interface_port axi4stream_master tready tready Input 1


# 
# connection point clock_reset
# 
add_interface clock_reset clock end
set_interface_property clock_reset ENABLED true
set_interface_property clock_reset EXPORT_OF ""
set_interface_property clock_reset PORT_NAME_MAP ""
set_interface_property clock_reset CMSIS_SVD_VARIABLES ""
set_interface_property clock_reset SVD_ADDRESS_GROUP ""
set_interface_property clock_reset IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property clock_reset SV_INTERFACE_TYPE ""
set_interface_property clock_reset SV_INTERFACE_MODPORT_TYPE ""

add_interface_port clock_reset clk clk Input 1


# 
# connection point clock_reset_reset
# 
add_interface clock_reset_reset reset end
set_interface_property clock_reset_reset associatedClock clock_reset
set_interface_property clock_reset_reset synchronousEdges DEASSERT
set_interface_property clock_reset_reset ENABLED true
set_interface_property clock_reset_reset EXPORT_OF ""
set_interface_property clock_reset_reset PORT_NAME_MAP ""
set_interface_property clock_reset_reset CMSIS_SVD_VARIABLES ""
set_interface_property clock_reset_reset SVD_ADDRESS_GROUP ""
set_interface_property clock_reset_reset IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property clock_reset_reset SV_INTERFACE_TYPE ""
set_interface_property clock_reset_reset SV_INTERFACE_MODPORT_TYPE ""

add_interface_port clock_reset_reset reset_n reset_n Input 1

